project(sv C)
set(${PROJECT_NAME}_VENDOR "uael")
set(${PROJECT_NAME}_CONTACT "github.com/uael/sv/issues")
set(${PROJECT_NAME}_SUMMARY "libsv - Public domain cross-platform semantic versioning in c99")
set(${PROJECT_NAME}_MAJOR 1)
set(${PROJECT_NAME}_MINOR 0)
set(${PROJECT_NAME}_PATCH 0)
set(${PROJECT_NAME}_README README.md)
set(${PROJECT_NAME}_LICENSE UNLICENSE)
set(${PROJECT_NAME}_COMPILE_OPTIONS -Wno-missing-field-initializers)